# Generated by Django 5.0.6 on 2025-09-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial_fix'),
    ]

    operations = [
    ]
