# Generated by Django 5.0.6 on 2025-09-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_placeholder_0004'),
    ]

    operations = [
    ]
