# Generated by Django 5.0.6 on 2025-09-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ar/models/')),
                ('marker_image', models.ImageField(blank=True, null=True, upload_to='ar/markers/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_url', models.URLField(blank=True)),
                ('rotation_deg', models.CharField(default='0,0,0', max_length=50)),
                ('scale', models.FloatField(default=1.0)),
                ('info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/objects/')),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('offset_z', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='ar.arscene')),
            ],
        ),
    ]
