# Generated by Django 5.0.6 on 2025-09-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_objects', to='ar.arscene'),
        ),
    ]
